### ISSUE TITLE
Should screenshot API allow you to specify where to write the file to? Or document API better

### ISSUE THREAD

**Issue by alechenninger** [darcy-framework/darcy-web#43]
Right now I think it is maybe unnecessarily annoying that you have to move the File / write it to a new location to keep the screenshot. Also, it is undocumented that this is the behavior since this is just how WebDriver works (but if this is our contract of this API, we should document it here, so it is kept regardless of implementation).

However, an alternative could be to, for instance, pass a `Writer` to the function and then you could pass a `StringWriter` or a `FileWriter` or whatever. There are a few other options too.

What do you guys think?

@abocz @dmcneil @jvervaec

**Comment by dmcneil** [comment]
I could see the value of an API *alongside* the current, basic one that does what you're saying. Reason I say alongside rather than replacing the current is what if you don't necessarily care about writing the `File` anywhere?

Something that came to mind (and this is may be far-fetched examples) would be a consumer wanting to POST/upload or even email a multipart file using something like Apache's HttpClient or JavaMail APIs to send attachments which (IIRC?) typically just use either `String` paths or `File`.

I think at the very least the current API should be kept as is and anything else just added as a type of overload. The documentation should be added but I see the value in WebDriver simply returning a `File` that the consumer can then handle in any way they want. It's a bit more *work* to have to move the `File` but I think the simplicity of the current API gives a consumer flexibility in what they want to do with the screenshot once they have it.

With that being said, it could be argued that another API that would except some kind of `Writer` wouldn't really be necessary but act as just a shortcut/helper method to save some time and then is it really up to a WebDriver implementation to provide those means?

**Comment by alechenninger** [comment]
Actually, presumably an image is byte-based not character-based so replace `Writer` with `OutputStream`.

Similarly though, If you have an `OutputStream` API you have more flexibility for less work IMO. The only time it saves you work is if all you want is a temporary file. But in those examples you want either a File persisted somewhere on your filesystem, or you want it as bytes to send with something else. In both of those examples a `OutputStream` API would be easier.

```java
File screenshotFile = Paths.get("...").toFile();
// Could also use Files.createTempFile there ^
FileOutputStream fileOut = new FileOutputStream(screenshotFile);
browser.takeScreenshot(fileOut);
```

```java
ByteArrayOutputStream bytesOut = new ByteArrayOutputStream();
browser.takeScreenshot(bytesOut);
```

Compared today to the cumbersome code you have to use to copy the temporary file somewhere.

What do you think?

**Comment by alechenninger** [comment]
> Compared today to the cumbersome code you have to use to copy the temporary file somewhere.
...or extract the bytes from the file if all you want is the content.

**Comment by dmcneil** [comment]
I'm a bit confused on how that `FileOutputStream` makes things any easier with a temporary file. You're still going to have to move/copy it to wherever your desired destination is once the `screenshotFile` has been written to via the `OutputStream` aren't you? 

Since using `Files#createTempFile` creates a file in a temporary directory (`/tmp` for example) then you're basically back to where you were with the current `File`-returning API and just using some kind of `FileUtils#copyFile` or something after to move said file to where you want it like a reports folder. 

As for not using `Files#createTempFile` if you did:
```
File screenshotFile = new File("target/screenshots/example.png");
FileOutputStream fileOut = new FileOutputStream(screenshotFile);
browser.takeScreenshot(fileOut);
```

That would work but I think you would have to throw some extra logic in there to create any folders that may not exist at the time. Like in our use case, `target` may not exist due to `mvn clean` and `screenshots` wouldn't exist initially either so you're going to get `FileNotFoundException` that other libraries already take into account/address when moving files and create any necessary directories/folders that don't exist.

Perhaps I'm just misunderstanding/missing basic `OutputStream` usage and/or not getting what the new `takeScreenshot(OutputStream outputStream)` implementation would be doing besides just calling `write`, `flush`, and `close`.

**Comment by alechenninger** [comment]
You don't need to copy the file if you just write to end destination you want. Keep in mind that FileUtils you're mentioning is in another library. Just using an output stream only requires the JDK. Gotta run, will reread your reply in more detail later :).

**Comment by dmcneil** [comment]
Yeah understandable, I was just getting at that while that example *works*, I think you would need to use something like `File#mkdirs` or `Files#createDirectories` to 'prepare' the destination file to be written if the folders aren't guaranteed to exist ahead of time otherwise you'll run into `FileNotFoundExeception'. It just seems like it's not any less work than utilizing a library that does the preparation/heavy lifting for you.

**Comment by alechenninger** [comment]
Yeah, it's not any less work, but you don't _need_ to use a library to have that less work. Also, it's not very apples to apples: using an `OutputStream` affords you flexibility and is more explicit. You pass to the method something that contains knowledge about where to put this image data. What I don't like about the current design is it gives you a temporary `File` that you have to deal with, and that's not really the most natural way to deal with things most of the time (it encourages you to use another library to deal with it, after all!). It's also not very clear from the API that this file is temporary. Passing something makes this explicit.

So yeah, the implementation would get the bytes from underlying library and write, flush, close, but it's more polymorphic. It doesn't care what it is writing to.

The most concise example I think that has the same functionality is this:

```java
Path screenshot = Paths.get("target/screenshots");
Files.createDirectories(screenshot);
OutputStream fileOut = Files.newOutputStream(screenshot);
browser.takeScreenshot(fileOut);
```

Which does not require another library, is explicit, and only 15 more characters than (same number of method calls):

```java
Path keptScreenshot = Paths.get("target/screenshots");
File tempScreenshot = browser.takeScreenshot();
FileUtils.copyFile(tempScreenshot, keptScreenshot.toFile());
```

I know we iterated a bit on this previously, I think what we got wrong was focusing on the method returning something rather than using something passed to it (sort of visitor-pattern-ish).

**Comment by alechenninger** [comment]
To be fair actually you can avoid the library argument by using `Files.copy(tempScreenshot, keptScreenshot)`, but the other arguments still apply (namely, not being explicit that you should deal with this temp file).

**Comment by alechenninger** [comment]
We could also do overloaded versions still, I'm just not crazy about the temp file thing anymore, why not...

```java
Path screenshot = Paths.get("target/screenshots/foo.png");
browser.takeScreenshot(screenshot);
```

**Comment by alechenninger** [comment]
And in that case, have the `OutputStream` API there that implementations have to implement, and the `Path` version could have a `default` implementation which did the create directories bit and created the output stream.

**Comment by dmcneil** [comment]
Ah, okay, those examples definitely clarify the vision; I'm sold. As you mentioned before (and *somewhat* similar to how Selenium does it with the `OutputType`)...something along these lines was the initial plan anyways before deciding on just outputting a `File` because it was easier. So yeah, I would agree using an `OutputStream` has the benefits of the original Selenium-ish way of using `OutputType` but with even more flexibility.

I probably shouldn't argue "more work" if it's the same number of method calls and only 2 more seconds of typing out characters :) Plus, nothing wrong with some JDK standard lib purity in a case like this.

I also like the ideas of utilizing  `default` for the more specific use cases: if the code lives in one place it's not really "more work" either since there's no need to constantly have to type out the `FileUtils`/copying stuff wherever you need to. 

+1

I can work on putting together something for this.
